import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import Faqs from "@/components/common/Faqs";
import GetInTouch from "@/components/common/GetInTouch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Faqs />
        <GetInTouch />
        <Footer />
      </body>
    </html>
  );
}
